import { ArrowUpRight } from 'lucide-react';
import { Link } from 'react-router-dom';

const projects = [
  { id: 'atlas', type: 'Product design · 2024', title: 'Atlas Finance', copy: 'Making investing feel less intimidating for a new generation.', image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85', className: 'md:col-span-7' },
  { id: 'morrow', type: 'Brand identity · 2023', title: 'Morrow Studio', copy: 'A warmer identity for a studio shaping the future of work.', image: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=1200&q=85', className: 'md:col-span-5' },
  { id: 'fieldnotes', type: 'Web development · 2023', title: 'Field Notes', copy: 'A calm digital home for curious people and big questions.', image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=85', className: 'md:col-span-5' },
  { id: 'lumen', type: 'Product design · 2022', title: 'Lumen Health', copy: 'Putting better daily habits within easy reach.', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=85', className: 'md:col-span-7' }
];

export default function Projects() {
  return <section id="work" className="bg-ink py-24 text-white lg:py-32"><div className="container-shell"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow text-blue-400">Selected work</p><h2 className="mt-4 font-display text-4xl font-bold tracking-tight sm:text-5xl">A few things I&apos;ve<br /><span className="text-slate-500">helped bring to life.</span></h2></div><p className="max-w-xs text-sm leading-6 text-slate-400">A small selection of recent collaborations across product, brand, and technology.</p></div><div className="mt-14 grid gap-8 md:grid-cols-12">{projects.map((project, index) => <article key={project.id} className={project.className}><Link to={`/project/${project.id}`} className="group block"><div className="relative overflow-hidden bg-slate-800"><img loading={index === 0 ? 'eager' : 'lazy'} decoding="async" className="aspect-[1.25/1] w-full object-cover transition duration-700 group-hover:scale-105" src={project.image} alt={project.title} /><div className="absolute inset-0 bg-ink/0 transition group-hover:bg-ink/10" /></div><div className="mt-5 flex items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-400">{project.type}</p><h3 className="mt-2 font-display text-2xl font-bold">{project.title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-slate-400">{project.copy}</p></div><span className="flex h-10 w-10 shrink-0 items-center justify-center border border-slate-700 transition group-hover:border-blue-400 group-hover:text-blue-400"><ArrowUpRight size={18} /></span></div></Link></article>)}</div></div></section>;
}
